import config
from  models import *
import json
import os 
import shutil

os.environ['CUDA_VISIBLE_DEVICES']='5'
con = config.Config()
con.set_in_path("./benchmarks/FB15K/")
con.set_work_threads(8)
con.set_train_times(5000)
con.set_nbatches(100)
con.set_alpha(0.001)
con.set_bern(1)
con.set_dimension(100)
con.set_margin(1.5)
con.set_ent_neg_rate(0)
con.set_rel_neg_rate(1)
con.set_prob_rel(True)
con.set_opt_method("SGD")
con.set_save_steps(10)
con.set_valid_steps(10)
con.set_early_stopping_patience(20)
con.set_checkpoint_dir("./checkpoint")
con.set_result_dir("./result")
con.set_main_target('Relation')
con.set_hit_target('1')
con.set_val_loss(False)
con.set_valid_link(False)
con.set_valid_relation(True)
con.set_test_link(False)
con.set_test_relation(True)
con.set_test_triple(False)
con.set_SA(True)
con.set_SA_steps(200)
con.set_SA_temp(8192, 16)
con.init()
con.set_train_model(TransE)
shutil.copyfile('./train_transE.py', os.path.join(con.checkpoint_dir, 'train_transE.py'))
shutil.copyfile('./config/Config.py', os.path.join(con.checkpoint_dir, 'Config.py'))
# con.set_pretrain_model("")
con.train()
# con.set_test_model(con.model, './checkpoint/TransE.ckpt')
# con.test()
